---
root: true
parserOptions:
  ecmaVersion: 6
env:
  node: true
  es6: true
extends: 'eslint:recommended'
rules:
  block-scoped-var: 2
  comma-dangle: [2, always-multiline]
  consistent-return: 2
  curly: 2
  dot-location: [2, property]
  dot-notation: 2
  eqeqeq: 2
  global-require: 2
  handle-callback-err: [2, error]
  no-console: 0
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-multi-spaces: 2
  no-new-wrappers: 2
  no-new: 2
  no-proto: 2
  no-sequences: 2
  no-shadow:
    - 2
    - allow:
      - error
      - callback
      - result
  no-shadow-restricted-names: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-use-before-define:
    - 2
    - functions: false
  no-useless-call: 2
  radix: 2
  strict: [2, global]
  wrap-iife: [2, inside]
  yoda: [2, never]

  array-bracket-spacing: [2, never]
  brace-style: [2, 1tbs]
  camelcase:
    - 2
    - properties: never
  comma-spacing: 2
  comma-style: 2
  eol-last: 2
  indent: [2, tab]
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style: [2, unix]
  lines-around-comment:
    - 2
    - beforeBlockComment: true
      beforeLineComment: true
      allowBlockStart: true
      allowObjectStart: true
      allowArrayStart: true
  new-cap: 2
  new-parens: 2
  no-array-constructor: 2
  no-multiple-empty-lines: 2
  no-new-object: 2
  no-spaced-func: 2
  no-trailing-spaces: 2
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  object-curly-spacing: [2, always]
  one-var: [2, never]
  operator-linebreak: [2, after]
  padded-blocks: [2, never]
  quotes: [2, double, avoid-escape]
  semi: [2, always]
  semi-spacing: 2
  space-before-function-paren:
    - 2
    - anonymous: always
      named: never
  space-before-blocks: 2
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: 2
