---
parserOptions:
  ecmaVersion: 5
env:
  browser: true
  node: false
  es6: false
globals:
  def: false
  require: false
rules:
  global-require: 0
  no-shadow:
    - 2
    - allow:
      - e
  no-var: 0
